### ISSUE TITLE
Zoom Points argument

### ISSUE THREAD

**Issue by ezawadzki** [DOsinga/pydroste#11]
Hi,

I am trying to use multiple version, I got this error :

` error: unrecognized arguments: --zoom_points=122,475,125;287,486,125
`

With this command : 

```
python pydroste_multiple.py --input=eiffeltower.jpg \
                   --output=effeiltower.mp4 \
                   --zoom_points='122,475,125;287,486,125'
```

I dive into you pydroste_multiple.py to take an example.

What am I doing wrong ?

Thanks

**Comment by DOsinga** [comment]
Oops. Looks like a bug. It imports from the normal pydroste and that then ends up setting the arguments. If you copy the zoom_at function and remove the import I think it should work

**Comment by ezawadzki** [comment]
And it works !
